phrase = ("this is calculator which")
print("     ")
print("     ")
print("     ")
print("      /\          => " + phrase.upper())
print("     /  \           => hepls you to calculate ".upper())
print("    /    \             => the powers of the numbers".upper())
print("   /      \     ")
print("  /        \             =>  enter first number that you want find square of ".upper())
print(" /          \              =>  and next enter for what power you want".upper())
print("/____________\     ")
print("                           ,,,,,,,,,,,,,,,,,,,,,,,")
print("                           | dhnanush calculator |".upper())
print("                            ``````````````````````    ")
print("     ")
print("     ")
x = input("enter a number: ")
y = input("enter another number: ")
print(pow(float(x), float(y)))
