print("     ")
print("     ")
print("     ")
print("      /\           this is calculator which")
print("     /  \            hepls you to calculate ")
print("    /    \              the powers of the numbers")
print("   /      \     ")
print("  /        \               enter first number that you want find square of ")
print(" /          \                and next enter for what power you want")
print("/____________\ ")
print("                 dhnanush calculator")
print("     ")
print("     ")
print("     ")
x = input("enter a number: ")
y = input("enter another number: ")
print(pow(int(x), int(y)))
